#%RAML 1.0
version: v1
baseUri: https://mocksvc.mulesoft.com/mocks/9c1865f4-d938-491a-8a82-132feb331377 # 
title: Accounts API

types:
  Account: !include types/account.raml
  AccountNoID: !include types/accountNoID.raml

/accounts:        
  get:
      headers: 
        Requester-ID:
          type: string
          example: "10"

      description: Obtener todas las cuentas
      queryParameters: 
        name:
          type: string
          required: false
          enum: 
            - personal
            - business
          example: "personal"
        country:
          type: string 
          required: false
          example: "Argentina"
      
      responses: 
        200:
          body: 
            application/json:
              type: Account []
              example: !include examples/accountsExample.raml
    
  post:
    description: Agregar una cuenta
    body: 
      application/json:
        type: AccountNoID
        example: !include examples/accountNoIDExample.raml
    responses: 
      201:
        body: 
          application/json:
            example:
              message: {"mensaje": "Cuenta creada (pero no realmente)"}
  /{id}:
    get:
     description: Obtener cuenta por ID
     responses:
      200:
        body:
          application/json:
            type: Account
            example: !include examples/accountExample.raml       
              
    put:
      description: Reemplazar una cuenta
      body:
        aplication/json:
          type: AccountNoID
          example: !include examples/accountNoIDExample.raml
      
      responses:
        200:
          body:
            application/json:
              example:
                {"mensaje":"Cuenta reemplazada (pero no realmente)"}
     
    patch:
      description: Modificar una cuenta
      body:
        aplication/json:
          type: AccountNoID
          example: !include examples/accountNoIDExample.raml
      
      responses:
        200:
          body:
            application/json:
              example:
                {"mensaje":"Cuenta eliminada (pero no realmente)"}
    
    delete:
      description: Eliminar una cuenta  
      responses:
        200:
          body:
            application/json:
              example:
                {"mensaje":"Cuenta eliminada (pero no realmente)"}
         
        