#%RAML 1.0 NamedExample
value:

-
  firstName: Gonzalo
  lastName: Bertinat
  address: Sarmiento 1230
  postal: 1014
  country: Argentina
  miles: 1500
  accountType: string

-
  firstName: Gonzalo
  lastName: Bertinat
  address: Sarmiento 1230
  postal: 1014
  country: Argentina
  miles: 1500
  accountType: string